name: Deploy to minecraft VPS

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest
    
    steps:
      - name: Install SSH keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_SECRET_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H 194.87.56.213 > ~/.ssh/known_hosts

      - name: Connect and pull
        run: ssh admin@194.87.56.213 "sudo project/minecraft-server/scripts/deploy.sh"

      - name: Cleanup
        run: rm -rf ~/.ssh
